version: '3.8'

services:
  db:
    image: postgres:16
    container_name: wave808-db
    restart: always
    environment:
      POSTGRES_USER: CAMBIAR!!!
      POSTGRES_PASSWORD: CAMBIAR!!!
      POSTGRES_DB: wave808_db
    ports:
      - "5433:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data